name: 'Fetch DockerHub Metadata'
description: 'Get metadata of a Docker image hosted on DockerHub'
author: 'Theo Brown'
inputs:
  repository:
    required: true
    description: 'DockerHub repository name (e.g. myuser/myrepo)'
  tag:
    required: true
    default: latest
    description: 'Docker image tag (default: latest)'
outputs:
  metadata:
    description: 'Metadata of Docker image'
runs:
  using: 'node12'
  main: 'dist/index.js'
