name: 'Example workflow'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  fetch-metadata-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch-metadata
        uses: ./
        with:
          repository: theobrown/fetch-dockerhub-metadata-test
          tag: 1
      - name: another-step
        run: |
          echo "Labels fetched from DockerHub: ${{ steps.fetch-metadata.outputs.labels }}"
